---
title: "proj4"
author: "Jingtian Yao"
date: "April 9, 2018"
output: html_document
---

```{r}
library(plyr)
library(reshape)
library(reshape2)

train <- read.csv("~/Columbia Courses/2nd semester/GR5243/data_sample/data_sample/MS_sample/data_train.csv")
train <- train[,-1]
uniq <- unique(train$V2)
num_vroot <- length(uniq[nchar(uniq)==4])
num_user <- length(uniq)-num_vroot

idx_c <- which(train$V1=="C")
user_id <- as.character(train[idx_c,2])
user_visits <- diff(idx_c)-1 
user_visits <- c(user_visits,
                 nrow(train)-idx_c[length(idx_c)])

user <- rep(user_id,user_visits)

temp <- train[-idx_c,]
temp$user <- user
temp <- temp[,-1]
colnames(temp) <- c("vroot","click","user")
temp <- temp[,c(1,3,2)]

wide <- dcast(temp,user~...)

#train <- train[-idx_c,]
#train$user <- user
#train <- train[,-1]
#colnames(train) <- c("vroot","click","user")
#write.csv(train,"train_MS.csv")

mat <- matrix(rep(0,num_user*num_vroot),
                       nrow = num_user)

```


```{r}
library(reshape)
library(reshape2)

process_MS <- function(df,export = FALSE){
  uniq <- unique(df$V2)
  user_id <- as.character(uniq[nchar(uniq)==5])
  vroot_id <- setdiff(uniq,user_id)
  num_user <- length(user_id)
  num_vroot <- length(vroot_id)
  
  idx_c <- which(df$V1=="C")
  user_visits <- diff(idx_c)-1 
  user_visits <- c(user_visits,
                 nrow(df)-idx_c[length(idx_c)])
  user <- rep(user_id,user_visits)
  
  temp <- df[-idx_c,]
  temp$user <- user
  temp <- temp[,-c(1,2)]
  colnames(temp) <- c("vroot","click","user")
  temp <- temp[,c(1,3,2)]
  wide <- dcast(temp,user~...)
  if(export){
    write.csv("MS_process.csv")
  }
  return(wide)
}

wide_train <- process_MS(train)
test <- read.csv("~/Columbia Courses/2nd semester/GR5243/data_sample/data_sample/MS_sample/data_test.csv")
wide_test <- process_MS(test)
write.csv(wide_test, "test_1.csv")

```

